name: build
on:
  workflow_dispatch:

jobs:
  build:
    name: Build cli
    runs-on: macos-11
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make osx
